server:
  port: 8081
  servlet:
    context-path: /demo

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  datasource:
    url: jdbc:sqlserver://10.3.21.83:1433;DatabaseName=common_dev
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: common_user
    password: Password@1
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置
    initialSize: 1
    minIdle: 1
    maxIdle: 30
    maxActive: 300
    maxWait: 50
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    #每个数据库都不一样的 注意要
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    #慢SQL记录 如果上面validationQuery: SELECT 1 没有配置，而你配置了就会报错null
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500




